name: fi_widget
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.1
  kartal: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
